// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdolr--XrpRST3lQd2hzvo4AAq9l4GDcg',
    appId: '1:677105148061:web:6ac93943fc465855dab474',
    messagingSenderId: '677105148061',
    projectId: 'renting-app-2028c',
    authDomain: 'renting-app-2028c.firebaseapp.com',
    storageBucket: 'renting-app-2028c.appspot.com',
    measurementId: 'G-10SKL9TNBE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChCTsQkCVzYADNjtUrvy25mKX3JhjiJd0',
    appId: '1:677105148061:android:8abbc7a07a2d096bdab474',
    messagingSenderId: '677105148061',
    projectId: 'renting-app-2028c',
    storageBucket: 'renting-app-2028c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD517eoKlM24Whwls-9pmb0oYQeHo3uiEo',
    appId: '1:677105148061:ios:3efef88a0df9396adab474',
    messagingSenderId: '677105148061',
    projectId: 'renting-app-2028c',
    storageBucket: 'renting-app-2028c.appspot.com',
    iosClientId: '677105148061-eq811j2vbk7ubfi4qefgdnbcpjrnhvtn.apps.googleusercontent.com',
    iosBundleId: 'com.rental.shop',
  );
}
